hospitalproject/hospitalapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',homepage,name='homepage'),
    path('login/',my_login,name='login'),
    path('head/',head,name='head'),
    path('doctor/',doctor,name='doctor'),
    path('patient/',patient,name='patient'),
    path('department/',department,name="department"),
    path('doctorupdate/<int:id>/',doctorupdate,name="doctorupdate"),
    path('adddoctor/',adddoctor,name='adddoctor'),
    path('deletedoctor/<int:id>/',deletedoctor,name='deletedoctor'),
    path('updatepatient/<int:id>/',updatepatient,name='updatepatient'),
    path('deletepatient/<int:id>/',deletepatient,name='deletepatient'),
    path('homedoctors/',homedoctors,name='homedoctors'),
    path('timeslots/<int:id>/',timeslots,name='timeslot'),
    path('mybookappointment/',book_appointment,name='book_appointment'),
    # path('selecttimeslot/<int:id>/',select_slot,name='selectslot')
    path('selecttimeslot/',select_slot,name='selecttimesslot'),
    path('logout/',my_logout,name='logout'),
    # path('pdf/',venue_pdf,name='venue_pdf'),
    path('personaldoctor/',personaldoctor,name='personaldoctor'),
    path('doctorpatient/',patientdoctor,name='patientdoctor'),
    path('writereport/<int:id>/',write_report,name='writereport')
]   

hospitalproject/hospitalproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hospitalapp.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hospitalproject/hospitalapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin
from .managers import CustomUserManager
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
import pytz
import datetime
from django.utils import timezone
# Create your models here.

class CustomUser(AbstractBaseUser,PermissionsMixin):
    
    name = models.CharField(max_length=50,null=True,blank=True)
    email = models.EmailField(verbose_name="email",max_length=60,unique=True)
    password=models.CharField(max_length=6,unique=True)
    is_active= models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


    objects=CustomUserManager()





DEPARTMENT_CHOICES=(('Dental','Dental'),
                    ('Cardiology','Cardiology'),
                    ('Urology','Urology'),
                    ('Plastic Surgery','Plastic Surgery'),
                    ('Nerology','Nerology'))

class Department(models.Model):
    department=models.CharField(max_length=264,choices=DEPARTMENT_CHOICES,default='')

    def __str__(self):
        return self.department



# class Patient(models.Model):
#     name=models.CharField(max_length=50,null=True,blank=True)
#     phone=models.IntegerField(max_length=50,null=True,blank=True)
#     email = models.EmailField(verbose_name="email",max_length=60,unique=True)

    # def __str__(self):
    #         return self.name




class Doctor(models.Model):
    first_name=models.CharField(max_length=50,null=True,blank=True)
    last_name=models.CharField(max_length=50,null=True,blank=True)
    email = models.EmailField(verbose_name="email",max_length=60)
    qualification=models.CharField(max_length=264,null=True,blank=True)
    area_of_expertise=models.CharField(max_length=264,null=True,blank=True)
    book_appointent=models.ManyToManyField('BookAppointment',symmetrical=False,default='',blank=True,null=True)  
    fees=models.IntegerField(null=True,blank=True)
    department=models.ForeignKey(Department,default='',null=True,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.first_name)

  
    # def __str__(self):
    #     return str(self.patient.all())


# class Appointment(models.Models):
#     doctor=models.ForeignKey(Doctor,on_delete=models.CASCADE)
#     patinet_name=models.CharField(max_length=50,null=True,blank=True)
#     patient_phone=models.IntegerField(max_length=50,null=True,blank=True)
#     patient_email = models.EmailField(verbose_name="email",max_length=60,unique=True)
#     time_slot=models.DateTimeField(blank=True)

class DoctorTimeSlot(models.Model):
    doctor=models.ForeignKey(Doctor,on_delete=models.CASCADE)
    date=models.DateField(null=True,blank=True)
    start_time=models.TimeField(null=True,blank=True)
    end_time=models.TimeField(null=True,blank=True)
    booked=models.BooleanField(default=False)
    slots_available=models.IntegerField(default=0,null=True,blank=True)

    def __str__(self):
        return str(self.start_time)
    

# @receiver(post_save,sender=DoctorTimeSlot)
# def save_doctortimeslot(sender,instance,created,**kwargs):
#     doctor=DoctorTimeSlot.objects.get(id=instance.id)
#     start_time=str(doctor.start_time)
#     end_time=str(doctor.end_time)
#     def time_slots(start_time, end_time):
#         print(start_time,type(start_time))
#         print(end_time,type(end_time))
#         t = start_time
#         while t <= end_time:
#             yield t.strftime('%H:%M:%S')
#             t = (datetime.datetime.combine(datetime.date.today(), t) +
#                 datetime.timedelta(minutes=15)).time()
#     t1,m1,s1=int(start_time[:2]),int(start_time[3:5]),int(start_time[6:9])
#     t2,m2,s2=int(end_time[:2]),int(end_time[3:5]),int(end_time[6:9])
#     start_time=datetime.time(t1,m1,s1)
#     end_time=datetime.time(t2,m2,s2)
#     print(list(time_slots(start_time,end_time)))

# post_save.connect(save_doctortimeslot,sender=DoctorTimeSlot)



class BookAppointment(models.Model):
    mydoctor=models.ForeignKey(Doctor,on_delete=models.CASCADE)
    start_time=models.TimeField(default=timezone.now())
    end_time=models.TimeField(default=timezone.now())
    patinet_name=models.CharField(max_length=50,null=True,blank=True)
    patient_phone=models.CharField(max_length=10,null=True,blank=True)
    patient_email = models.EmailField(verbose_name="email",max_length=60,unique=True)
    file_upload=models.FileField(upload_to='documents')

    
    











   

hospitalproject/templates/adddoctor.html
{%extends 'adminpage.html'%}

{%block adminpage%}
{% load crispy_forms_tags %}
{%for message in messages%}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
  <strong>Message:</strong> {{message}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{%endfor%}
<br>
<center>
<div class='container'>
<form method='post'>
{%csrf_token%}
{{form|crispy}}
<br>
<input type='submit' value='Submit' class='btn btn-primary btn-sm'>
</form>
</div>
</center>

{%endblock%}

hospitalproject/templates/adminpage.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Welcome Page</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="#">Hospital Managent System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/logout">Logout <span class="sr-only">(current)</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Doctor
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/adddoctor">Add Doctor</a>
          <a class="dropdown-item" href="/doctor">All Doctors</a>
          {% comment %} <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>  {% endcomment %}
          </div>


       {% comment %} <li class="nav-item">
        <a class="nav-link" href="/patient">Patient <span class="sr-only">(current)</a>
      </li> {% endcomment %}

       <li class="nav-item">
        <a class="nav-link" href="/patient">Patient<span class="sr-only">(current)</a>
      </li>
      
        
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    
  </div>
</nav>

{%block adminpage%}
        {%endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> 
   
  </body>
</html>

hospitalproject/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <title>Welcome Page</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="#">Hospital Managent System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/login">Login <span class="sr-only">(current)</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          For Patients and visitor
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/homedoctors">Doctor</a>
          <a class="dropdown-item" href="/mybookappointment">Make An Appointment</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/pdf">Generate Pdf</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{%block base%}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1505751172876-fa1923c5c528?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGhvc3BpdGFsfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1505751172876-fa1923c5c528?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGhvc3BpdGFsfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1505751172876-fa1923c5c528?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGhvc3BpdGFsfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{%endblock%}
    
  </body>
</html>

hospitalproject/templates/bookappointment.html
{%extends 'base.html'%}

{%block base%}
{% load crispy_forms_tags %}
<br>
  {%for message in messages%}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
  <strong>Message:</strong> {{message}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{%endfor%}
<center>
<div class='container'>
<form method='post'>
  <div class="form-group">
  
    <label for="exampleFormControlSelect1">Select Doctor</label>
    <select class="form-control" id="doctor" name='mydoctor'>
     <option>Please Select Doctor</option>
    {%for x in timeslot%}
      <option value={{x.id}}>{{x.first_name}}</option>
      {%endfor%}
    </select>
   
  </div>
<div class="form-group">
    <label for="timeslot">Select TimeSlot</label>
    <select class="form-control" id="timeslot" name='mytimeslot'>
      <option></option>
    </select>
    {% comment %} <div class="form-group">
    <label for="patient_name">Available Time Slot</label>
    <input type="text" class="form-control" id="availabletimeslot" name='patientname' aria-describedby="emailHelp" placeholder="Enter Patient Name" disabled >
  </div> {% endcomment %}
  </div>
  <form method='post'>
  {%csrf_token%}
  <div class="form-group">
    <label for="patient_name">Patient Name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name='patientname' aria-describedby="emailHelp" placeholder="Enter Patient Name" required >
  </div>
   <div class="form-group">
    <label for="patient_name">Patient Phone</label>
    <input type="text" class="form-control" maxlength="10" name='patientphone'id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Patient Name" required>
  </div>
   <div class="form-group">
    <label for="patient_name">Patient Email</label>
    <input type="text" class="form-control" name='patientemail' id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Patient Name" required>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</center>
 <script>
$('#doctor').change(function(){
  data=$('#doctor').val()
  console.log("---- ",data)
  if (data==='Please Select Doctor'){
    $('#timeslot').prop('disabled','disabled')
    $('#timeslot').empty()
    console.log('it is working')
  }else{
  
      $('#timeslot').prop('disabled',false)
    
    $.ajax({
             type: "GET",
             url:"{% url 'selecttimesslot'%}",
             data:{"id":$(this).children(":selected").attr('value')},
             dataType: "json",
             success:function(data){
               var to_append=''
               var available_timeslot=''
               var len=data.length;
               for(i=0;i<len;i++){
               var id=data[i].id;
               var start_time=data[i].start_time;
               var end_time=data[i].end_time;
               to_append+="<option value='"+start_time+' '+end_time+"'>"+start_time+' '+end_time+'</option>';
               }
               $('#timeslot').html(to_append)
               
             }
             })
  }
  })
</script>
{%endblock%}

hospitalproject/templates/doctor.html
{%extends 'adminpage.html'%}

{%block adminpage%}
<br>
<form method='get' action='/department'>
Choose Department:<select class="custom-select" name='select'>
  <option value=1>Dental</option>
  <option value=2>Cardiology</option>
  <option value=3>Urology</option>
  <option value=4>Plastic Surgery</option>
  <option value=5>Nerology</option>
</select>
<input type='submit' class='btn btn-primary btn-sm' value='search'>
</form>
<br>


<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Qualification</th>
      <th scope="col">Area of Expertise</th>
      <th scope="col">Department</th>
      <th scope='col'>Patient</th>
      <th scope="col">Fees</th>
      <th scope="col">Activity</th>
    </tr>
  </thead>
  <tbody>
  {%for data in doctor%}
    <tr>
      <td>{{data.first_name}} &nbsp;{{data.last_name}}</td>
      <td>{{data.qualification}}</td>
      <td>{{data.area_of_expertise}}</td>
      <td>{{data.department}}</td>
      <td>{%for x in data.book_appointent.all%}
      {{x.patinet_name}}
      {%endfor%} 
      </td>
      <td>{{data.fees}}</td>
      <td><a href='/doctorupdate/{{data.id}}/' class='btn btn-primary'>Update</a>&nbsp;<a href='/deletedoctor/{{data.id}}/' class='btn btn-danger'>Delete</a>&nbsp;
      <a href="/timeslots/{{data.id}}/" class='btn btn-primary'>TimeSlots</a></td>

    </tr>
    {%endfor%}
</table>
{%endblock%}

hospitalproject/templates/doctorpatient.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h2>Patient Details</h2>

    <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Consultant Name</th>
      <th scope="col">Start Time</th>
      <th scope="col">End Time</th>
      <th scope="col">Patient Name</th>
      <th scope='col'>Patient Phone</th>
      <th scope="col">Patient Email</th>
      <th scope="col">Activity</th>
    </tr>
  </thead>
  <tbody>
  {%for data in patient%}
    <tr>
      <td>{{data.mydoctor}}</td>
      <td>{{data.start_time}}</td>
      <td>{{data.end_time}}</td>
      <td>{{data.patinet_name}}</td>
      <td>{{data.patient_phone}}</td>
      <td>{{data.patient_email}}</td>
      <td><a href='/writereport/{{data.id}}/' class='btn btn-primary'>Write Report</a></td>
      <tr>
      {%endfor%}
    </tbody>
    </table>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

hospitalproject/templates/doctorupdate.html
{%extends 'adminpage.html'%}

{%block adminpage%}
{% load crispy_forms_tags %}
<br>
<center>
<div class='container'>
<form method='post'>
{%csrf_token%}
{{form|crispy}}
<br>
<input type='submit' value='Submit' class='btn btn-primary btn-sm'>
</form>
</div>
</center>

{%endblock%}

hospitalproject/templates/homedoctor.html
{%extends 'base.html'%}

{%block base%}
<br>
<form method='get' action='/homedoctors'>
Choose Department:<select class="custom-select" name='select'>
  <option value=1>Dental</option>
  <option value=2>Cardiology</option>
  <option value=3>Urology</option>
  <option value=4>Plastic Surgery</option>
  <option value=5>Nerology</option>
</select>
<input type='submit' class='btn btn-primary btn-sm' value='search'>
</form>
<br>


<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Qualification</th>
      <th scope="col">Area of Expertise</th>
      <th scope="col">Department</th>
      <th scope="col">Fees</th>
    </tr>
  </thead>
  <tbody>
  {%for data in doctor%}
    <tr>
      <td>{{data.first_name}} &nbsp;{{data.last_name}}</td>
      <td>{{data.qualification}}</td>
      <td>{{data.area_of_expertise}}</td>
      <td>{{data.department}}</td>
      <td>{{data.fees}}</td>
    </tr>
    {%endfor%}
</table>
{%endblock%}

hospitalproject/templates/login.html
{%extends 'base.html'%}

{%block base%}
<div class='container my-5'>
  <form method='POST'>
  {{form.as_p}}{{message}}
   {% csrf_token %}
    <input type='submit' value='Login' class='btn btn-primary'>
    
    </form>
    </div>
  </center>
{%endblock%}

hospitalproject/templates/patient.html
{%extends 'adminpage.html'%}

{%block adminpage%}


<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Consultants</th>
      <th scope="col">Start Time</th>
      <th scope="col">End Time</th>
      <th scope="col">Report</th>
      <th scope="col">Activity</th>

    </tr>
  </thead>
  <tbody>
  {%for data in patients%}
    <tr>
      <td>{{data.patinet_name}}</td>
      <td>{{data.patient_email}}</td>
      <td>{{data.patient_phone}}</td>
      <td>{{data.mydoctor}}</td>
      <td>{{data.start_time}}</td>
      <td>{{data.end_time}}</td>
      <td><a href="{{data.file_upload.url}}" class="btn btn-primary">Report</a></td>

      {% comment %} <td>{%for x in data.doctor_set.all%}
      {{x.first_name}} {% endcomment %}
      <td><a href='/updatepatient/{{data.id}}/' class='btn btn-primary'>Update</a>&nbsp;<a href='/deletepatient/{{data.id}}/' class='btn btn-danger'>Delete</a></td>
    </tr>
    {%endfor%}
</table>
{%endblock%}

hospitalproject/templates/timeslots.html
{%extends 'adminpage.html'%}
{%block adminpage%}
<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Date</th>
      <th scope="col">Start Time</th>
      <th scope="col">End Time</th>
      <th scope="col">Book</th>
      <th scope="col">Available Slot</th>
    </tr>
  </thead>
  <tbody>
  {%for data in timeslot%}
    <tr>
      <td>{{data.doctor}}</td>
      <td>{{data.date}}</td>
      <td>{{data.start_time}}</td>
      <td>{{data.end_time}}</td>
      <td>{{data.booked}}</td>
      <td>{{data.slots_available}}</td>
    </tr>
    {%endfor%}
</table>
        {%endblock%}